"""add is_active soft delete

Revision ID: 1e893180b777
Revises: 9a16238f84a7
Create Date: 2026-06-17 22:42:20.149607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e893180b777'
down_revision: Union[str, None] = '9a16238f84a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_index('uq_customers_email_active', 'customers', ['email'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.add_column('orders', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_constraint(op.f('products_sku_code_key'), 'products', type_='unique')
    op.create_index('uq_products_sku_code_active', 'products', ['sku_code'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_products_sku_code_active', table_name='products', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint(op.f('products_sku_code_key'), 'products', ['sku_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'is_active')
    op.drop_column('orders', 'is_active')
    op.drop_index('uq_customers_email_active', table_name='customers', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
